#----------------------------------------------------------------
# Travis-CI configuration for R packages
#
# REFERENCES:
# * Travis CI: https://docs.travis-ci.com/user/languages/r
# * covr: https://github.com/jimhester/covr
#
# Validate your .travis.yml file at http://lint.travis-ci.org/
#----------------------------------------------------------------
language: r
sudo: false
cache: packages
warnings_are_errors: false
r_check_args: --as-cran

matrix:
  include:
    - os: linux
      r: oldrel
      r_packages:
        - survival
      bioc_packages:
        - BiocInstaller
    - os: linux
      r: release
      r_packages:
        - survival
    - os: linux
      r: devel
    - os: osx
      r: oldrel
      bioc_packages:
        - BiocInstaller
    - os: osx
      r: release
    - os: linux
      r: release
      r_check_args: --no-build-vignettes --no-codoc --no-examples --no-tests --no-manual --ignore-vignettes
      r_packages:
        - covr
      after_success:
        - Rscript -e 'covr::codecov(quiet=FALSE)'
      env: NB='w/ covr' ## Just a label

notifications:
  email:
    on_success: change
    on_failure: change
