#----------------------------------------------------------------
# AppVeyor configuration for R packages
#
# REFERENCES:
# * AppVeyor CI: https://ci.appveyor.com/
# * r-travis: https://github.com/craigcitro/r-travis
# * covr: https://github.com/jimhester/covr
# * Coveralls: https://coveralls.io/
#
# Validate your .appveyor.yml file at
# https://ci.appveyor.com/tools/validate-yaml 
#----------------------------------------------------------------
environment:
  _R_CHECK_FORCE_SUGGESTS_: false
  RENV: travis-tool.sh

# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/HenrikBengtsson/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'
install:
  ps: Bootstrap

# Adapt as necessary starting from here

build_script:
 - $RENV install_bioc DNAcopy
 - $RENV install_bioc aroma.light
 - $RENV install_r matrixStats R.cache R.methodsS3 R.oo R.utils
 - $RENV install_r ggplot2 Hmisc R.devices R.rsp

test_script:
  - $RENV run_tests

on_failure:
  - $RENV dump_logs

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
